### PR TITLE
Fix cd command

### LINKED ISSUE #226: cd directory with whitespace
Tried to access my drive: `cd Google\ Dri` which obviously didn't work.

Then typed `fuck`, but it reran the cmd as `cd /Users/kengz/Google Drive/`, when it really should have been `cd /Users/kengz/Google\ Drive/` (note the slash after "Google").

### PR DESCRIPTION
**Pull request by mcarton**
Fix #226

### CODE REVIEW

**Comment by nvbn** [comment]
Thanks!

**Comment by kengz** [comment]
Hello, I just ran --upgrade `thefuck` and retried it. The same issue seems to persist. I'm on OSX if that helps.

**Comment by dunn** [comment]
There hasn't been a stable release since this fix.  If you have Homebrew you can use `brew install --HEAD thefuck` to build the master branch.

**Comment by nvbn** [comment]
@kengz stable release will be on the weekend, I need to code some stuff before it.

**Pull request merged**
