### PR TITLE
fix usage. why not

### PR DESCRIPTION
**Pull request by myoung34**

### CODE REVIEW

**Comment by nvbn** [comment]
Actually project name is The Fuck =)

**Comment by mcarton** [comment]
@nvbn Yes but that's the *usage* section of the help:
```
% thefuck
usage: The Fuck [-h] [-v] [-a] [command [command ...]]
```
it should be
```
% thefuck
usage: thefuck [-h] [-v] [-a] [command [command ...]]
```
as that's what you would write to execute the program.

**Comment by myoung34** [comment]
@nvbn  ^^ that was what I was attempting to fix.

all command usage lists the command, not the human readable application name.

**Comment by nvbn** [comment]
@mcarton misread the patch.
@myoung34 thanks!

**Pull request merged**
