### PR TITLE
custom fuckups with --ifuckedup

### PR DESCRIPTION
**Pull request by underscorejho**
Added learning ability to `thefuck`. #163 

```
-$ cd..
cd..: command not found
-$ fuck --ifuckedup 'cd ..'
Adding fucked: cd.. as fixed: cd ..
-$ fuck --remove 'cd..'
Removing fucked: cd.. as fixed: cd ..
```

### CODE REVIEW

**Comment by underscorejho** [comment]
fixing bugs...

**Comment by sullyj3** [comment]
Personal opinion: I prefer your original name for the option, "add_fuckup", over "ifuckedup". "add_fuckup" makes it clearer what it's for. Whereas "ifuckedup" is ambiguous, you fucked up every time you need to type fuck, not just when you need to add a new rule.

**Comment by underscorejho** [comment]
You make a good point. If @nvbn agrees, I'll change that.

**Comment by nvbn** [comment]
It's a cool idea, but we can't use command line arguments, because previous command can be `cmd --remove` or something, and for this situation `fuck` wouldn't work.

**Comment by underscorejho** [comment]
I'm going to make some changes first to make sure that this is true, but I believe I can build it so that it's only looking at command line args from the relevant `fuck` command, instead of the 'fucked up' command. That way `fuck --remove` wouldn't interfere with `cmd --remove`.

**Comment by underscorejho** [comment]
I've changed the get_command() function in main.py to programmatically fetch the previous command using .bash_history . This eliminates the need for the current alias, though it requires lines in .bashrc to keep .bash_history up to date. 

I believe this should work, but I'm having trouble adjusting the appropriate tests.

**Comment by sullyj3** [comment]
Does it work with zsh and fish?

**Pull request closed without merging**
