### PR TITLE
Absolute path feature for cd_correction

### PR DESCRIPTION
**Pull request by alexbarcelo**
This is motivated by #784 

According to my understandment of the code, this should fix the scenario of "`dest` starts with `/`". However, I had some problems with local tests and still I am not sure if I am overlooking some corner case.

### CODE REVIEW

**Comment by scorphus** [comment]
How willing are you to write tests for this rule?

**Comment by alexbarcelo** [comment]
Can do.

This WE I suppose I will complete the PR then.

**Comment by alexbarcelo** [comment]
There are no unittest for the correction, but that needs filesystem so... not very unittest-able I'm afraid.

@scorphus, are the provided basic tests ok? Do you feel that the new functional is enough for the cd_correction? `coveralls` doesn't detect the executed code in functional tests as covered (AFAIK), but the functional should indeed be testing that.

**Comment by alexbarcelo** [comment]
There are no unittest for the correction, but that needs filesystem so... not very unittest-able I'm afraid.

@scorphus, are the provided basic tests ok? Do you feel that the new functional is enough for the cd_correction? `coveralls` doesn't detect the executed code in functional tests as covered (AFAIK), but the functional should indeed be testing that.

**Comment by nvbn** [comment]
Thanks!

We don't actually use functional tests for rules, because it's too slow, so I removed it.

**Comment by nvbn** [comment]
I squashed commits manually, it's not just closed, but merged =)

**Pull request closed without merging**
