### PR TITLE
[deprecated] Add Python 3.8 version support

### PR DESCRIPTION
**Pull request by duboviy**

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
the 2nd and 4th commit can just be dropped.

**Comment by duboviy** [comment]
> the 2nd and 4th commit can just be dropped.

Thanks. Created #983 instead (PR without useless commits).

**Comment by SuperSandro2000** [comment]
> > the 2nd and 4th commit can just be dropped.
> 
> Thanks. Created #983 instead (PR without useless commits).

You should learn git and how to use rebase and force push.

**Comment by duboviy** [comment]
> > > the 2nd and 4th commit can just be dropped.
> > 
> > 
> > Thanks. Created #983 instead (PR without useless commits).
> 
> You should learn git and how to use rebase and force push.

Sorry, I'm doing commits via mobile app (on vacation).

**Pull request closed without merging**
