### PR TITLE
python2.7 unicode error

### PR DESCRIPTION
**Pull request by lovedboy**

### CODE REVIEW

**Comment by lovedboy** [comment]
@nvbn  Finally,both py2 and py3 are Travis CI build passed

**Comment by scorphus** [comment]
Ok, @lovedboy. I'll rebase my work on top of yours and continue from there.

**Comment by lovedboy** [comment]
@scorphus :)

**Comment by scorphus** [comment]
@lovedboy Can you please squash these two commits into one? :smiley: Then `git push --force <your_remote>/master` to, as you probably already know, updates this pull request. Thank you!

**Comment by lovedboy** [comment]
@scorphus Okay.

**Pull request merged**
