### PR TITLE
fix Unicode Encode Error

### PR DESCRIPTION
**Pull request by lovedboy**

### CODE REVIEW

**Comment by lovedboy** [comment]
when i run `git commt -am "你好"` then `fuck` will get follow error msg:
```
Traceback (most recent call last):
  File "/Users/superadmin/Desktop/git/thefuck/thefuck/types.py", line 222, in is_match
    if compatibility_call(self.match, command):
  File "/Users/superadmin/Desktop/git/thefuck/thefuck/utils.py", line 242, in compatibility_call
    return fn(*args)
  File "<decorator-gen-103>", line 2, in match
  File "/Users/superadmin/Desktop/git/thefuck/thefuck/specific/sudo.py", line 10, in sudo_support
    return fn(command)
  File "/Users/superadmin/Desktop/git/thefuck/thefuck/rules/no_command.py", line 8, in match
    return (command.script_parts
  File "/Users/superadmin/Desktop/git/thefuck/thefuck/types.py", line 35, in script_parts
    self, sys.exc_info()))
  File "/Users/superadmin/Desktop/git/thefuck/thefuck/types.py", line 48, in __repr__
    self.script, self.stdout, self.stderr)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 15-16: ordinal not in range(128)
```

**Comment by scorphus** [comment]
@lovedboy I'm not sure if you're aware of current open issues – #398 for example – about this problem. I'm in the middle of tackling it, I can share my progress once I get home, in a few hours.

**Comment by lovedboy** [comment]
@scorphus Yep. The latest 3.2 version don't support Chinese. :)

**Comment by lovedboy** [comment]
@scorphus If you're handling this, I am free.

**Pull request closed without merging**
