### PR TITLE
Cleanup `pacman` rule

### PR DESCRIPTION
**Pull request by mcarton**

### CODE REVIEW

**Comment by mcarton** [comment]
I wonder how I could write a test for that one since it depends on the external program `pkgfile`.

**Comment by scorphus** [comment]
You can check pull request #200 (more precisely: https://github.com/scorphus/thefuck/blob/improve-shells/tests/rules/test_pacman.py)

**Comment by mcarton** [comment]
I just merged conflicts with #200.
@scorphus:
Did you test that on Arch Linux?
On mine tests did not pass as `pkgfile` returns the complete name of the package (eg. `extra/gvim` for `vim`). I fixed that in 031669f.

**Comment by scorphus** [comment]
@mcarton: That's awesome!

These last days I've struggled trying to `vagrant up` an Archlinux to run those tests. I haven't had any near-to-good Internet connection so far since Tuesday. So, thank you!

What do you think about fixing the `*mocked` tests as well?

**Comment by mcarton** [comment]
@scorphus: I do not know mock but for what I understand I should replace
```
Command('vim'), '{} -S vim && vim'.format(pacman_cmd), 'vim foo bar'),
```
with something like:
```
Command('vim'), '{} -S vim && vim'.format(pacman_cmd), 'extra/gvim\nextra/gvim-python3'),
```
since `pkgfile` output is as follow:
```
% pkgfile vim
extra/gvim
extra/gvim-python3
extra/vim
extra/vim-minimal
extra/vim-python3
```
Can you confirm that?

**Comment by scorphus** [comment]
Not quite that... almost! `rules/pacman.py` has:
```python
        # [snip]
        return subprocess.check_output(
            ['pkgfile', '-b', '-v', command.script.split(" ")[0]],
            universal_newlines=True, stderr=DEVNULL
        ).split()
        # [snip]
```
And I get the following form `pkgfile`:
```shell
vagrant@archlinux:~$ sudo pkgfile -b -v vim
extra/gvim 7.4.723-1        	/usr/bin/vim
extra/gvim-python3 7.4.723-1	/usr/bin/vim
extra/vim 7.4.723-1         	/usr/bin/vim
extra/vim-minimal 7.4.723-1 	/usr/bin/vim
extra/vim-python3 7.4.723-1 	/usr/bin/vim
vagrant@archlinux:~$ 
vagrant@archlinux:~$ sudo pkgfile -b -v convert
extra/imagemagick 6.9.1.0-2	/usr/bin/convert
```

**Comment by mcarton** [comment]
Yes I know, I just wanted to be sure `return_value` was supposed to be the output of `pkgfile` and forgot the flags in my example. Anyway, it should be right now, this can be merged.

**Comment by nvbn** [comment]
Thanks!

**Pull request merged**
