### PR TITLE
Added the --bash-alias command to output the alias

### PR DESCRIPTION
**Pull request by WhoBrokeTheBuild**
Added the following command output the correct alias line to add to your .bashrc so you can call it like:
thefuck --bash-alias >> ~/.bashrc

This would be the implementation for issue #131

### CODE REVIEW

**Comment by nvbn** [comment]
We can't use cli arguments in this app, reason why:
```bash
➜ someapp --bash-alias  
zsh: command not found: someapp
➜  fuck  # And it just sets new alias
➜ alias fuck
fuck=\''eval'
```

**Comment by SanketDG** [comment]
[Docopt](https://github.com/docopt/docopt) maybe? I don't know if it would work out, as @nvbn pointed out.

**Comment by nvbn** [comment]
@SanketDG docopt, optparse and argparse can't help.

@WhoBrokeTheBuild  only way to do this properly - introduce new `entry_point`, like `thefuck-alias`.

**Comment by SanketDG** [comment]
@nvbn That would be silly though, anybody would hardly use it that way.

**Comment by nvbn** [comment]
@SanketDG what difference between `thefuck --alias` and `thefuck-alias`?

**Comment by SanketDG** [comment]
Well people are generally habituated to use command line arguements, but I guess this would be a workaround.

**Pull request closed without merging**
