### PR TITLE
Add rule for hostscli

### PR DESCRIPTION
**Pull request by dhilipsiva**
Add rule for: https://github.com/dhilipsiva/hostscli

### CODE REVIEW

**Comment by dhilipsiva** [comment]
@nvbn Should I change something in this PR? I hope I have done this correctly. 😛

**Comment by nvbn** [comment]
I suggest a few changes:
* remove comments/doctrings at the top of files;
* move sudo-related stuff to `sudo` rule;
* for `no_command` case try to find most similar command, like, for example, in `react_native_command_unrecognized` rule.

**Comment by dhilipsiva** [comment]
@nvbn Thanks for your suggestions.

1. Apologies. That is my default vim template
2. Moved to sudo rule 👍 
3. I hope I implemented the similar command properly. 

Please do let me know if this required any further changes.

**Comment by nvbn** [comment]
Thanks!

**Pull request merged**
