### PR TITLE
Readme fixes

### PR DESCRIPTION
**Pull request by tpltnt**
Hi nvbn,

I added some info to the README to help others who run into similar problems.
Cheers,
tpltnt

### CODE REVIEW

**Comment by revmischa** [comment]
learn to spell, dummy

**Comment by tpltnt** [comment]
Thank you for pointing it out. Since you seem to have a knack for it, I welcome a sincere pull request.

**Comment by nvbn** [comment]
Hi tpltnt,

It's maybe a wrong steps, there's was a little error in app.
Is your error repeats with new version and without steps in diff?

**Comment by tpltnt** [comment]
@delasteve you are right. Thank you for correcting me.

**Comment by tpltnt** [comment]
@nvbn I am reinstalling thefuck (version 1.12.) directly via pip and it still fails.

**Comment by nvbn** [comment]
@tpltnt what os and shell are you using?

**Comment by tpltnt** [comment]
I tested it on FreeBSD with zsh (in a VM).

**Comment by nvbn** [comment]
Is it repeats with 1.29+?

**Pull request closed without merging**
