### PR TITLE
Fix slowness problems II

### PR DESCRIPTION
**Pull request by mcarton**
The `brew_*` rules were really slow (importing them had a lot of side effect) but they are not well tested. Someone should definitely test them (I don't have an OS X).
This will only buy us a few milliseconds.

Ref #334.

### CODE REVIEW

**Comment by scorphus** [comment]
I can test them for you:
```
============================= test session starts ==============================
platform darwin -- Python 2.7.9 -- py-1.4.30 -- pytest-2.7.2 -- /Users/pablo/.virtualenvs/thefuck/bin/python2.7
rootdir: /Users/pablo/Workspace/thefuck, inifile: 
plugins: cov, mock
collecting ... collected 6 items

tests/rules/test_brew_install.py::test_match PASSED
tests/rules/test_brew_install.py::test_get_new_command PASSED
tests/rules/test_brew_unknown_command.py::test_match FAILED
tests/rules/test_brew_unknown_command.py::test_get_new_command FAILED
tests/rules/test_brew_upgrade.py::test_match[command0] PASSED
tests/rules/test_brew_upgrade.py::test_get_new_command[command0-brew upgrade --all] PASSED

=================================== FAILURES ===================================
__________________________________ test_match __________________________________

brew_unknown_cmd = 'Error: Unknown command: inst'

    def test_match(brew_unknown_cmd):
>       assert match(Command('brew inst', stderr=brew_unknown_cmd), None)

tests/rules/test_brew_unknown_command.py:18: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
thefuck/rules/brew_unknown_command.py:73: in match
    return bool(get_closest(broken_cmd, _brew_commands()))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    def _brew_commands():
        brew_path_prefix = get_brew_path_prefix()
        if brew_path_prefix:
            try:
                return _get_brew_commands(brew_path_prefix) \
>                    + _get_brew_tap_specific_commands(brew_path_prefix)
E                    TypeError: unsupported operand type(s) for +: 'generator' and 'list'

thefuck/rules/brew_unknown_command.py:56: TypeError
_____________________________ test_get_new_command _____________________________

brew_unknown_cmd = 'Error: Unknown command: inst'
brew_unknown_cmd2 = 'Error: Unknown command: instaa'

    def test_get_new_command(brew_unknown_cmd, brew_unknown_cmd2):
>       assert get_new_command(Command('brew inst', stderr=brew_unknown_cmd),
                               None) == ['brew list', 'brew install', 'brew uninstall']

tests/rules/test_brew_unknown_command.py:24: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
thefuck/rules/brew_unknown_command.py:80: in get_new_command
    return replace_command(command, broken_cmd, _brew_commands())
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    def _brew_commands():
        brew_path_prefix = get_brew_path_prefix()
        if brew_path_prefix:
            try:
                return _get_brew_commands(brew_path_prefix) \
>                    + _get_brew_tap_specific_commands(brew_path_prefix)
E                    TypeError: unsupported operand type(s) for +: 'generator' and 'list'

thefuck/rules/brew_unknown_command.py:56: TypeError
====================== 2 failed, 4 passed in 0.17 seconds ======================
```

Same thing for Python 3

**Comment by mcarton** [comment]
Thanks, the coverage of that rule is not really good.

**Comment by scorphus** [comment]
I can work on that later today, what you say?

-- 
Pablo Aguiar (scorphus) <scorphus@gmail.com>

**Comment by scorphus** [comment]
Almost there...
```
============================= test session starts ==============================
platform darwin -- Python 3.4.3 -- py-1.4.30 -- pytest-2.7.2 -- /Users/pablo/.virtualenvs/thefuck-py3/bin/python3.4
rootdir: /Users/pablo/Workspace/thefuck, inifile: 
plugins: benchmark, cov, mock
collecting ... collected 6 items

tests/rules/test_brew_install.py::test_match PASSED
tests/rules/test_brew_install.py::test_get_new_command PASSED
tests/rules/test_brew_unknown_command.py::test_match PASSED
tests/rules/test_brew_unknown_command.py::test_get_new_command FAILED
tests/rules/test_brew_upgrade.py::test_match[command0] PASSED
tests/rules/test_brew_upgrade.py::test_get_new_command[command0-brew upgrade --all] PASSED

=================================== FAILURES ===================================
_____________________________ test_get_new_command _____________________________

brew_unknown_cmd = 'Error: Unknown command: inst'
brew_unknown_cmd2 = 'Error: Unknown command: instaa'

    def test_get_new_command(brew_unknown_cmd, brew_unknown_cmd2):
        assert get_new_command(Command('brew inst', stderr=brew_unknown_cmd),
                               None) == ['brew list', 'brew install', 'brew uninstall']
    
>       assert get_new_command(Command('brew instaa', stderr=brew_unknown_cmd2),
                               None) == ['brew install', 'brew uninstall', 'brew list']
E       assert ['brew instal...ew reinstall'] == ['brew install..., 'brew list']
E         At index 2 diff: 'brew reinstall' != 'brew list'
E         Full diff:
E         - ['brew install', 'brew uninstall', 'brew reinstall']
E         ?                                          ^^ -  ---
E         + ['brew install', 'brew uninstall', 'brew list']
E         ?                                          ^

tests/rules/test_brew_unknown_command.py:27: AssertionError
====================== 1 failed, 5 passed in 0.22 seconds ======================
```

**Comment by scorphus** [comment]
Just apply:
```diff
diff --git a/tests/rules/test_brew_unknown_command.py b/tests/rules/test_brew_unknown_command.py
index 17adb47..86bec5b 100644
--- a/tests/rules/test_brew_unknown_command.py
+++ b/tests/rules/test_brew_unknown_command.py
@@ -25,4 +25,4 @@ def test_get_new_command(brew_unknown_cmd, brew_unknown_cmd2):
                            None) == ['brew list', 'brew install', 'brew uninstall']
 
     assert get_new_command(Command('brew instaa', stderr=brew_unknown_cmd2),
-                           None) == ['brew install', 'brew uninstall', 'brew list']
+                           None) == ['brew install', 'brew uninstall', 'brew reinstall']
```
and we are go.

**Comment by mcarton** [comment]
@scorphus Thanks, that might work on OS X but does not work on Linux anymore ([including travis](https://travis-ci.org/nvbn/thefuck/builds/77458656)) :p
I probably have fixed it now, but it's mostly a hack with a weaken test. This test should be rewritten to do the same thing on Linux and OS X (or we should [ask for OS X testing on travis](http://docs.travis-ci.com/user/multi-os/) and not test it at all on Linux) and have a better coverage.

**Comment by scorphus** [comment]
No problem, @mcarton :smile: 

```py.test``` said:
> **635 passed, 52 skipped in 5.06 seconds** 

Tests tell us we're good to ~~python~~ go :+1: 

@mcarton said:
> [...] This test should be rewritten to do the same thing on Linux and OS X (...) and have a better coverage.

I can try and work on that :construction:

**Comment by nvbn** [comment]
Can I merge this, or it's in progress?

**Comment by mcarton** [comment]
@nvbn You can merge. scorphus helped my fix the tests on mac and I guess the easiest for him would to make another PR if he wants to improve the `brew_*` tests.

**Comment by scorphus** [comment]
Just give a chance to test this with zsh, as that other issue states it's slow for some reason. I'll test this in about one hour from now.

**Comment by scorphus** [comment]
And count on me for improving the brew tests

**Comment by scorphus** [comment]
I can confirm this changes make TheFuck faster on both Fish and Zsh. Thank you, @mcarton. :+1:

It LGTM, please merge it, @nvbn

**Comment by nvbn** [comment]
@mcarton, @scorphus Thanks!

**Pull request merged**
