### PR TITLE
#1141: Fix crash on empty history

### LINKED ISSUE #1141: thefuck crashes if the command is run twice after clearing command history
The output of `thefuck --version` (something like `The Fuck 3.1 using Python
3.5.0 and Bash 4.4.12(1)-release`):

    The Fuck 3.30 using Python 3.8.5 and Bash 5.0.17(1)-release

Your system (Debian 7, ArchLinux, Windows, etc.):

    Ubuntu 20.04.1 LTS

How to reproduce the bug:

   "$history -c", then "$fuck", then "$fuck"

The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):

     After first fuck-command
    bash: fc: history specification out of range
    DEBUG: Run with settings: {'alter_history': True,
    debug': True,
    env': {'GIT_TRACE': '1', 'LANG': 'C', 'LC_ALL': 'C'},
    exclude_rules': [],
    history_limit': None,
    instant_mode': False,
    no_colors': False,
    num_close_matches': 3,
    priority': {},
    repeat': False,
    require_confirmation': True,
    rules': [<const: All rules enabled>],
    slow_commands': ['lein', 'react-native', 'gradle', './gradlew', 'vagrant'],
    user_dir': PosixPath('/home/jesse/.config/thefuck'),
    wait_command': 3,
    wait_slow_command': 15}
    DEBUG: Empty command, nothing to do
    DEBUG: Total took: 0:00:00.000207

    After second fuck-command
    DEBUG: Run with settings: {'alter_history': True,
    debug': True,
    env': {'GIT_TRACE': '1', 'LANG': 'C', 'LC_ALL': 'C'},
    exclude_rules': [],
    history_limit': None,
    instant_mode': False,
    no_colors': False,
    num_close_matches': 3,
    priority': {},
    repeat': False,
    require_confirmation': True,
    rules': [<const: All rules enabled>],
    slow_commands': ['lein', 'react-native', 'gradle', './gradlew', 'vagrant'],
    user_dir': PosixPath('/home/jesse/.config/thefuck'),
    wait_command': 3,
    wait_slow_command': 15}
    DEBUG: Total took: 0:00:00.018500
    Traceback (most recent call last):
    File "/usr/local/bin/thefuck", line 8, in <module>
    sys.exit(main())
    File "/usr/local/lib/python3.8/dist-packages/thefuck/entrypoints/main.py", line 31, in main
    fix_command(known_args)
    File "/usr/local/lib/python3.8/dist-packages/thefuck/entrypoints/fix_command.py", line 36, in fix_command
    command = types.Command.from_raw_script(raw_command)
    File "/usr/local/lib/python3.8/dist-packages/thefuck/types.py", line 77, in from_raw_script
    script = format_raw_script(raw_script)
    File "/usr/local/lib/python3.8/dist-packages/thefuck/utils.py", line 335, in format_raw_script
    script = ' '.join(raw_script)
    TypeError: can only join an iterable

If the bug only appears with a specific application, the output of that application and its version:

    Also on Mint

Anything else you think is relevant:

    FILL THIS IN

### PR DESCRIPTION
**Pull request by divykj**
Fixes #1141

### CODE REVIEW

**Review by scorphus — COMMENTED** [review]
Perhaps a better fix might be done in `thefuck/utils.py` instead:

```diff
diff --git a/thefuck/utils.py b/thefuck/utils.py
index 8d55f37..bfc73d4 100644
--- a/thefuck/utils.py
+++ b/thefuck/utils.py
@@ -329,6 +329,9 @@ def format_raw_script(raw_script):
     :rtype: basestring
 
     """
+    if not raw_script:
+        return raw_script
+
     if six.PY2:
         script = ' '.join(arg.decode('utf-8') for arg in raw_script)
     else:
```

And with a bonus:

```diff
diff --git a/tests/test_types.py b/tests/test_types.py
index bea8f59..247bff6 100644
--- a/tests/test_types.py
+++ b/tests/test_types.py
@@ -139,6 +139,7 @@ class TestCommand(object):
                                       env=os_environ)
 
     @pytest.mark.parametrize('script, result', [
+        (None, None),
         ([''], None),
         (['', ''], None),
         (['ls', '-la'], 'ls -la'),
```

What do you think?

**Comment by divykj** [comment]
> Perhaps a better fix might be done in `thefuck/utils.py` instead

I think it's the `_get_raw_command` function's duty to return a command (list of tokens), be it an empty one, which I think is better denoted by `[]` rather than `None` (also remember, *Explicit is better than implicit*).

> And with a bonus:
> 
> ```diff
> diff --git a/tests/test_types.py b/tests/test_types.py
> index bea8f59..247bff6 100644
> --- a/tests/test_types.py
> +++ b/tests/test_types.py
> @@ -139,6 +139,7 @@ class TestCommand(object):
>                                        env=os_environ)
>  
>      @pytest.mark.parametrize('script, result', [
> +        (None, None),
>          ([''], None),
>          (['', ''], None),
>          (['ls', '-la'], 'ls -la'),
> ```
How about this:
```diff
diff --git a/tests/test_types.py b/tests/test_types.py
index bea8f59..247bff6 100644
--- a/tests/test_types.py
+++ b/tests/test_types.py
@@ -139,6 +139,7 @@ class TestCommand(object):
                                       env=os_environ)
 
     @pytest.mark.parametrize('script, result', [
+        ([], None),
         ([''], None),
         (['', ''], None),
         (['ls', '-la'], 'ls -la'),
```

**Review by scorphus — APPROVED** [review]
Yeah, it seemed to me that the issue was still there, i.e. `format_raw_string` not being able to deal with anything else other than an iterable. But that's exactly what it expects, so, I'm okay with that, although it still bothers me the fact that it does (or tries to do) unnecessary stuff with an empty list only to return something that could be returned earlier. IOW, and also correcting myself:

```diff
diff --git a/thefuck/utils.py b/thefuck/utils.py
index 8d55f37..c08ced3 100644
--- a/thefuck/utils.py
+++ b/thefuck/utils.py
@@ -329,6 +329,9 @@ def format_raw_script(raw_script):
     :rtype: basestring
 
     """
+    if not raw_script:
+        return ""
+
     if six.PY2:
         script = ' '.join(arg.decode('utf-8') for arg in raw_script)
     else:
```

**Comment by divykj** [comment]
> ```diff
> +    if not raw_script:
> +        return ""
> ```

@scorphus I feel you are looking into it too much, it is okay to call a `'  '.join` with an empty list, which in itself is a very very rare case. But adding this guard clause, which rarely gets executed is just unnecessary condition checking on every non-empty call (i.e. almost all of the calls).

**Comment by scorphus** [comment]
You're so right, @divykj. I guess I dug too deep into it 🙃 and overlooked the fact that it rarely receives an empty list. I'll merge this ASAP. Thanks!

**Pull request merged**
