### PR TITLE
Some fixes in REAME.md

### PR DESCRIPTION
**Pull request by mcarton**

### CODE REVIEW

**Comment by scorphus** [comment]
Nice catch! Totally forgot it. Thanks!

**Comment by mcarton** [comment]
You're welcome.

**Comment by nvbn** [comment]
Thanks!

**Comment by SanketDG** [comment]
Probably fix this [line](https://github.com/nvbn/thefuck/pull/283/files#diff-04c6e90faac2675aa89e2176d2eec7d8R204) too. It's confusing.

**Comment by mcarton** [comment]
@SanketDG: indeed it is. I modeled it as the `apt_get` rule but that *or* now makes it wrong. Would something like:
```
* `pacman` &ndash; installs app with `pacman` if it is not installed (uses `yaourt` if available).
```
be better?

**Pull request merged**
