### PR TITLE
Basic DNF support

### PR DESCRIPTION
**Pull request by Epse**
This PR contains basic support for `DNF` the Fedora package manager.

It contains a new specific, which only contains a variable `dnf_available`, very similar to `thefuck.specific.apt.apt_available`.

Also there is a `dnf_no_such_command` rule that parses `DNF`'s help output for commands and autofixes your input. It is enabled based on the `dnf_available` value.

`flake8` had no complaints about my code, but if you do, I'd welcome the advice!

### CODE REVIEW

**Comment by Epse** [comment]
It apears AppVeyor is broken...

**Comment by scorphus** [comment]
Nice! This one also lacks a proper test and a line in README.md explaining the new rule. Can you please add both? Thanks!

**Comment by Epse** [comment]
I assumed I shouldn't touch the README. Oh well, I'll fix it

**Comment by scorphus** [comment]
Looking good.

How about tests?

**Comment by Epse** [comment]
On their way. Running into a couple of issues where tests are failing but the same deal actually typed and fucked in a terminal works... Seems to be due to byte strings and regular strings

**Comment by Epse** [comment]
There are now tests!

**Comment by nvbn** [comment]
Thanks!

**Pull request merged**
