### PR TITLE
Added dpkg rule

### PR DESCRIPTION
**Pull request by Sclarki**
For example, when using ```dpkg -i some-pkg.deb```

### CODE REVIEW

**Comment by kingwood2112** [comment]
Hey,  wsup?

**Comment by SanketDG** [comment]
What have you changed, @Sclarki?

**Comment by Sclarki** [comment]
This should correct the mistake of trying to install a deb package without root. For example:

    $ dpkg -i some_pkg.deb
    dpkg: error: requested operation requires superuser privilege
    $ fuck
    sudo dpkg -i some_pkg.deb

**Comment by nvbn** [comment]
Thanks!

**Comment by kingwood2112** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- R

Confirm that you know R: https://www.linkedin.com/e/v2?e=cr76dq-i99jtlky-3h&amp;a=preRegInvite&amp;tracking=eml-guest-invite-cta&amp;ek=invite_guest&amp;sharedKey=qeLpWK1V&amp;invitationID=6000889217440325632


You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=cr76dq-i99jtlky-3h&amp;t=lun&amp;midToken=AQFmrFVhGEd36Q&amp;ek=invite_guest&amp;loid=AQFvKfMM23xWJwAAAU0dxCIBBr2mbSQHENAP6MR6iJ1sO1rCEKMz_3AWkEl8tbX4GioMdINOTyBbV0L6diHBucRWY6FnrdPXqctTBiMoqqvbh1RXhT2fo8QZrH-cPl-szAGmIF4xuSOL8EToLORfRxGD1HRCkOUbcmdsA3lofmX3U7rMfGSf9XVkGyRBNgFOwQaW&amp;eid=cr76dq-i99jtlky-3h Learn why we included this at the following link: https://www.linkedin.com/e/v2?e=cr76dq-i99jtlky-3h&a=customerServiceUrl&ek=invite_guest&articleId=4788
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by kingwood2112** [comment]
Download this http://talkray.com/dl/ee

**Comment by nwinkler** [comment]
I've reported @kingwood2112 to GitHub support for the above spam messages...

**Pull request merged**
