### PR TITLE
 Add support for the XDG Base Directory Specification #383

### PR DESCRIPTION
**Pull request by mcarton**
This is a redo of one of my oldest PR here (#160) that I got bored updating for nothing a while ago.
I'm obviously not the only one interested with that:
- #160 ;
- #383 *(explains well why this is useful)* ;
- https://github.com/andrewmichaud/thefuck/commit/a90c80ba534363430cb0ba3cafd2e9a288aa2c7a.

This is a non-breaking change.

### CODE REVIEW

**Comment by scorphus** [comment]
:+1:

How about moving `˜.thefuck` to `$XDG_CONFIG_HOME/thefuck` if the former exists?

**Comment by mcarton** [comment]
Maybe, but that would break the conf of people who currently back up
`~/.thefuck` or have `~/.thefuck` be a symlink to `~/.config/thefuck` to
be able to back up `./config` (such as me, so I'm a little biassed about
that :)).
Other tools that have adopted `$XDG_CONFIG_HOME` seem to keep the
historical directory for compatibility.

**Comment by SShrike** [comment]
I'm on the same page as @mcarton, moving a user's existing configuration is _not_ a good idea.

**Comment by scorphus** [comment]
Yeah, makes sense. I didn't think much about the complications it may raise.

**Comment by nvbn** [comment]
Thanks!
Currently `~/.thefuck` have a greater priority, then `~/.config/thefuck`, so it shouldn't break compatibility, even with old config's backups.

**Pull request merged**
