### PR TITLE
Custom fuckups rule -- no command line args

### PR DESCRIPTION
**Pull request by underscorejho**
version of #167 without command line args

### CODE REVIEW

**Comment by nvbn** [comment]
Why you use uppercase for variables?

**Comment by underscorejho** [comment]
I guess that's just my style. Upper case variables are more or less 'constants'. I can change that if you like.

**Comment by nvbn** [comment]
Nah, I'll change it by myself. I'll add support of `prepare` functions to rules and merge this pull request in nearest time =)

Also, there's convention in python community that variable written in uppercase is a constant, but it's not like `const` or `let`, it's more like `define`. So most of time it's a bad practice to use uppercase variable =)

**Comment by underscorejho** [comment]
Sweet. Thanks for the tip.

**Pull request closed without merging**
