### PR TITLE
add THEFUCK_HISTORY_LIMIT, my machine is so slow

### PR DESCRIPTION
**Pull request by lovedboy**
when my history commands is greater than 10000 lines, it will cost me one second to run fuck command. So i wish i can control how many history command the fuck will scan in order to match the closest command.

### CODE REVIEW

**Comment by lovedboy** [comment]
@nvbn Review the pull request :)

**Comment by nvbn** [comment]
All cool, but [thefuck/shells.py#L66](https://github.com/lovedboy/thefuck/blob/debug/thefuck/shells.py#L66) looks like rocket science.

Can you try branch `394-history-limit`, is it works fast on your machine?

**Comment by lovedboy** [comment]
@nvbn I just want to make certain that the history_limit variable is digit. :)
Before i open the pull request. I have a simple test. if i don't set the history limit , it cost more than one second to match the closest  command，sometimes worse. when I set the history_limit to 2000,it will just takes 0.1s or so. So this effect is what I want.

Any way, I will test the branch `394-history-limit` and @ you

**Comment by lovedboy** [comment]
@nvbn i just try the branch `394-history-limit`.

if i not set THEFUCK_HISTORY_LIMIT.
` DEBUG: Trying rule: history; took: 0:00:01.225300`
when i set THEFUCK_HISTORY_LIMIT=2000
`DEBUG: Trying rule: history; took: 0:00:00.343468`

more info:
```
➜  thefuck git:(394) ✗ wc -l ~/.zsh_history
   10027 /Users/superadmin/.zsh_history
```

**Comment by nvbn** [comment]
@lovedboy `394-history-limit` helped you and can merge it into master?

**Comment by lovedboy** [comment]
@nvbn  I think so. :)

**Pull request closed without merging**
