### PR TITLE
Added korean keyboard layout

### PR DESCRIPTION
**Pull request by yangkyeongmo**
Not only layout of korean keyboard but decomposing korean letters is also added.
If korean letter is written, it's automatically combined into one letter. ex) ㄱ + ㅏ = 가
So decomposing it was necessary.

### CODE REVIEW

**Comment by ik1ne** [comment]
Any update on this PR?
I also am a native Korean and I would appreciate it if you allow me to work on this PR.

**Comment by yangkyeongmo** [comment]
The implementation followed other successful implementations of other local languages. So if you can figure out why build failed, the rest might be easy.

**Comment by SuperSandro2000** [comment]
> Just to mention as the commiter: the implementation followed other successful implementations of other local languages. So if you can figure out why build failed, the rest might be easy.

I think AppVeyor already deleted the logs.

**Comment by ik1ne** [comment]
I finished rebasing this PR to upstream/master and added some test for coverage, with some minor modifications.
However I’m not sure whether I may open a new PR or somehow update this PR.

**Comment by SuperSandro2000** [comment]
>However I’m not sure whether I may open a new PR or somehow update this PR.

if you don't have push access to @yangkyeongmo repo you need to open a new PR.

**Pull request closed without merging**
