### PR TITLE
Test getting status code

### PR DESCRIPTION
**Pull request by davidhart82**
This, or something very similar, was what I hoped existed when I was implementing the `git commit - - amend` rule.

Do we think this, or a variant of it, might be useful? Before I do any more work on it.

### CODE REVIEW

**Comment by josephfrazier** [comment]
I was thinking the same thing when I saw https://github.com/nvbn/thefuck/pull/764#discussion_r159547506. I think it'd be useful, and would definitely welcome further work! I just merged #764, so this PR can build off of the new master and use `git_commit_amend` as the first rule to be tested.

It would also be nice to have functional tests that ensure the status code is actually being set properly, since the rule tests won't cover that.

**Comment by scorphus** [comment]
Great! I also thought about this some while ago, I just can't remember what rule made me think of it, but there are some other rules that might benefit from this as well.

**Comment by nvbn** [comment]
Sorry for slow response, it's great idea.

**Comment by davidhart82** [comment]
I'll revive this now I'm stuck at home; will look at these functional tests and try to decipher how they work.

**Pull request closed without merging**
