### PR TITLE
Add support for Python 3.10 and 3.11

### PR DESCRIPTION
**Pull request by hugovk**
Python 3.10 was released on 2021-10-04:

image

* https://discuss.python.org/t/python-3-10-0-is-now-available/10955

Drop the dot in `pytest`: 

* https://twitter.com/pytestdotorg/status/753767547866972160

Update min Python 3 version required in `README` to 3.5 to match `setup.py`.

Add `python_requires` to help pip.

### CODE REVIEW

**Comment by djh82** [comment]
This looks good?

**Comment by hugovk** [comment]
Yeah, it's actually time to start testing 3.11 beta (`3.11-dev`), but I guess one thing at a time :)

https://discuss.python.org/t/python-3-11-0b1-is-now-available/15602?u=hugovk

**Comment by hugovk** [comment]
Closing this year old PR due to lack of interest, but happy to re-open if wanted.

**Comment by scorphus** [comment]
phew

**Review by scorphus — APPROVED** [review]
Thanks, @hugovk! Apologies for the delay.

**Comment by hugovk** [comment]
Thanks for the finishing touches!

**Comment by Adawntoremember** [comment]
> This looks good?

**Pull request merged**
