### PR TITLE
Adding rule for forgotten '-r' when grepping folders

### PR DESCRIPTION
**Pull request by igorsantos07**
I guess it's straightforward to understand what it does :)

```
igor:~$ grep "is a directory" .
grep: .: Is a directory
igor:~$ fuck
grep -r "is a directory" .
dev/thefuck/tests/rules/test_rm_dir.py:7:    Command('rm foo', stderr='rm: foo: is a directory'),
dev/thefuck/thefuck/rules/grep_recursive.py:3:            and 'is a directory' in command.stderr.lower())
dev/thefuck/thefuck/rules/rm_dir.py:8:            and 'is a directory' in command.stderr.lower())
```

### CODE REVIEW

**Comment by scorphus** [comment]
LGTM :+1:

**Comment by scorphus** [comment]
One of the few pull requests with test! Nice job!

**Comment by nvbn** [comment]
Thanks!

**Comment by igorsantos07** [comment]
Hahaha thanks!

I'm a Python newbie and had issues to actually run `thefuck` locally, so
the test was useful to make sure I was not commiting BS :)

PS: code was based on copy paste from other files. As I said, noob here.
Haha

**Pull request merged**
