### PR TITLE
Added WTFPL license

### PR DESCRIPTION
**Pull request by pierlauro**
In my opinion this is the appropriate license for the project.

### CODE REVIEW

**Comment by Calinou** [comment]
The WTFPL lacks a warranty disclaimer, which means you could be sued for defects in the software.

Consider adding a warranty disclaimer to it.

Add this to the headers of code files:

```
/* This program is free software. It comes without any warranty, to
     * the extent permitted by applicable law. You can redistribute it
     * and/or modify it under the terms of the Do What The Fuck You Want
     * To Public License, Version 2, as published by Sam Hocevar. See
     * http://www.wtfpl.net/ for more details. */
```

**Comment by nvbn** [comment]
Nah, MIT is better =)

**Comment by revmischa** [comment]
My personal preference: https://github.com/landondyer/kasm/blob/master/LICENSE

**Comment by Calinou** [comment]
> My personal preference: https://github.com/landondyer/kasm/blob/master/LICENSE

This is non-free (and not open source) as there is discrimination against persons.

**Pull request closed without merging**
